### ISSUE TITLE
setup.py includes tests as a package

### ISSUE THREAD

**Issue by wykwit** [Skyscanner/whispers#52]
Currently `setup.py` uses simple `find_packages()` which includes 'tests', 'tests.unit', 'tests.unit.plugins' and 'tests.unit.rules' in a list of packages.
This results in `tests` being installed under site-packages, outside of `whispers` folder.
```
$ ls lib/python3.9/site-packages   
tests  whispers  whispers-1.4.7-py3.9.egg-info
```

The solution would be to use `find_packages()` with additional `exclude` parameter, like so:
```
find_packages(exclude=['tests', 'tests.*'])
```

**Comment by adeptex** [comment]
Hey @wykwit, interesting finding, thanks for raising! Let me have a look..
