### ISSUE TITLE
password env detect

### ISSUE THREAD

**Issue by markuman** [Skyscanner/whispers#62]
something like `isEnv: False ` when the password is read from env? e.g. for php 

```
{"file": "config/packages/doctrine.yaml", "line": 26, "key": "password", "value": "%env(resolve:DATABASE_PASSWORD)%", "message": "Password", "severity": "CRITICAL"}
```

but I guess that's hard to implement

**Comment by adeptex** [comment]
hey @markuman, thanks for posting for your question. 

Do you mean that you would like to avoid those placeholders in results? If yes - then yes, that is an improvement that can be done (and seeing your example, I would like to implement :] ). If that's not it, please explain further!

cheers
